CREATE TABLE "ED_DAILYLOG_TREATMENT"
(
	"ID" VARCHAR(36) NOT NULL,    -- 主键
	"DLOG_ID" VARCHAR(36),    -- 值班日志ID
	"DLOG_TREATMENT" VARCHAR(500),    -- 值班日志办理情况
	"TREAT_BY" VARCHAR(20),    -- 办理人
	"TREAT_TIME" DATE,    -- 办理时间(yyyy-MM-dd HH:mm:SS)
	"TREAT_STATUS" CHAR(1)    -- 日志办理状态码：0为待办，1为办理中，2为办结
)
;

COMMENT ON TABLE "ED_DAILYLOG_TREATMENT" IS '日志办理情况表'
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."ID" IS '主键'
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."DLOG_ID" IS '值班日志ID'
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."DLOG_TREATMENT" IS '值班日志办理情况'
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."TREAT_BY" IS '办理人'
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."TREAT_TIME" IS '办理时间(yyyy-MM-dd HH:mm:SS) '
;

COMMENT ON COLUMN "ED_DAILYLOG_TREATMENT"."TREAT_STATUS" IS '日志办理状态码：0为待办，1为办理中，2为办结 '
;

ALTER TABLE "ED_DAILYLOG_TREATMENT"
 ADD CONSTRAINT "PK_ED_DAILYLOG_TREATMENT"
	PRIMARY KEY ("ID") USING INDEX
;