swagger: '2.0'
info:
  description: >-
    突发事件信息接报、接报设置等。
  version: 1.0.0
  title: info接报信息
host: 127.0.0.1:8000
basePath: /info/v1

tags:
  - name: 信息接报管理infoDispatch
    description: 突发事件接收、报送信息管理
  - name: 接报设置管理infoConfig
    description: 接报设置信息管理

schemes:
  - http
paths:
####信息接报管理####
 /infoMags/searchInfoByButton:
    post:
      tags:
        - 信息接报管理infoDispatch
      summary: '根据条件查询信息列表-分页'
      operationId: findInfoReports
      parameters:
        - name: infoReportVo
          in: body
          required: true
          schema:
            type: object
            properties:
              buttonType:
                type: string
                description: 查询选择标签类型：00信息录入，01接收待办；10信息已办，11接收已办（后台操作：TYPE为00，则IM_ACCEPT_DEAL中CREATE_ORG_ID和DEAL_ORG_ID均为当前登录者所属单位ID，且DEAL_FLAG为0；TYPE为01，则IM_ACCEPT_DEAL中DEAL_ORG_ID为当前登录者所属单位ID，CREATE_ORG_ID不为当前登录者单位ID，且DEAL_FLAG为0；TYPE为10，则IM_ACCEPT_DEAL中CREATE_ORG_ID和DEAL_ORG_ID均为当前登录者所属单位ID，且DEAL_FLAG不等于0；TYPE为11，则IM_ACCEPT_DEAL中DEAL_ORG_ID为当前登录者所属单位ID，CREATE_ORG_ID不为当前登录者单位ID，且DEAL_DEAL_FLAG不等于0；获取ACCEPT_ID集合后再根据其他查询条件查询IM_ACCEPT表中对应的具体接报信息返回）
                enum:
                  - '00'
                  - '01'
                  - '10'
                  - '11'
              eventName:
                type: string
                description: 信息名称
              eventTypeIds:
                type: array
                description: eventTypeIds为事件类型选择Ids，数组
                items:
                  type: string
              eventGradeId:
                type: string
                description: 事件等级
              startDate:
                type: string
                format: date
                description: 事发时间——开始时间
              endDate:
                type: string
                format: date
                description: 事发时间——结束时间
            allOf:
              - $ref: '#/definitions/SearchBody'
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/IMAcceptList'
 /infoMags/:
   post:
     tags:
       - 信息接报管理infoDispatch
     summary: '信息填报，包括初报、续报，需同时更新IM_ACCEPT_DEAL表'
     operationId: addInfo
     parameters:
       - name: imAcceptVo
         in: body
         required: true
         schema:
           $ref: '#/definitions/IMAcceptVo'
     responses:
       200:
         description: ok
         schema:
           $ref: '#/definitions/ReturnResult'
 /infoMags/{id}:
   put:
     tags:
       - 信息接报管理infoDispatch
     summary: '修改信息'
     operationId: updateInfo
     parameters:
       - $ref: '#/parameters/id-p'
       - name: imAcceptVo
         in: body
         required: true
         schema:
           $ref: '#/definitions/IMAcceptVo'
     responses:
       200:
         description: ok
         schema:
           $ref: '#/definitions/ReturnResult'
   get:
     tags:
       - 信息接报管理infoDispatch
     summary: '获取单条上报、接报信息'
     operationId: findInfoReportById
     parameters:
       - $ref: '#/parameters/id-p'
     responses:
       200:
         description: ok
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               $ref: '#/definitions/IMAccept'
   delete:
     tags:
       - 信息接报管理infoDispatch
     summary: '删除信息'
     operationId: deleteInfo
     parameters:
       - $ref: '#/parameters/id-p'
     responses:
       200:
         description: ok
         schema:
           $ref: '#/definitions/ReturnResult'
 /infoMags/dealInfo:
   post:
     tags:
       - 信息接报管理infoDispatch
     summary: '办理信息，包括发送、退回、办结、生成/更新事件'
     operationId: dealInfo
     parameters:
       - name: buttonFlag
         in: query
         required: true
         type: string
         description: 按钮含义：发送1、退回2、办结3、生成事件4、更新事件5
       - name: infoDispatch
         in: body
         required: true
         schema:
           $ref: '#/definitions/IMAcceptDeal'
     responses:
       200:
         description: ok
         schema:
           $ref: '#/definitions/ReturnResult'
 /infoMags/checkReturnReason{id}:
   get:
     tags:
       - 信息接报管理infoDispatch
     summary: '查看退回原因'
     operationId: checkReturnReason
     parameters:
       - $ref: '#/parameters/id-p'
     responses:
       200:
         description: ok
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               $ref: '#/definitions/IMAcceptDeal'
 /infoMags/searchInfoByEvent:
   post:
     tags:
       - 信息接报管理infoDispatch
     summary: 通过事件ID，获取该事件下的全部初报、续报信息，先查询IM_ACCEPT_DEAL表，然后根据eventID，获取acceptID后再查详情
     operationId: getInfoListByEventId
     parameters:
       - name: eventId
         type: string
         in: query
         required: true
     responses:
       200:
         description: ok
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               type: array
               items:
                 $ref: '#/definitions/IMAccept'

 ####接报设置管理####
 /acceptInforms:
   post:
     tags:
       - 接报设置管理infoConfig
     summary: '新增通知单位'
     operationId: addAcceptInform
     parameters:
       - name: AcceptInform
         in: body
         required: true
         schema:
           $ref: '#/definitions/AcceptInform'
     responses:
       200:
         description: OK
         schema:
           $ref: '#/definitions/ReturnResult'
 /acceptInforms/{id}:
   get:
     tags:
       - 接报设置管理infoConfig
     summary: 获取单个通知单位信息
     operationId: findAcceptInformById
     parameters:
       - $ref: '#/parameters/id-p'
     responses:
       200:
         description:  OK
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               $ref: '#/definitions/AcceptInform'
   put:
     tags:
        - 接报设置管理infoConfig
     summary: '修改通知单位信息'
     operationId: updateAcceptInform
     parameters:
       - $ref: '#/parameters/id-p'
       - name: sms
         in: body
         required: true
         schema:
           $ref: '#/definitions/AcceptInform'
     responses:
       200:
         description: OK
         schema:
           $ref: '#/definitions/ReturnResult'
   delete:
     tags:
       - 接报设置管理infoConfig
     summary: '删除通知单位'
     operationId: deleteAcceptInform
     parameters:
       - $ref: '#/parameters/id-p'
     responses:
       200:
         description: OK
         schema:
           $ref: '#/definitions/ReturnResult'
 /acceptInforms/searchAll:
   post:
     tags:
       - 接报设置管理infoConfig
     summary: '根据条件查询通知单位列表'
     operationId: findAcceptInforms
     parameters:
       - name: acceptInformVO
         in: body
         required: true
         schema:
           type: object
           properties:
             eventTypeId:
               type: string
     responses:
       200:
         description: OK
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               type: array
               items:
                 $ref: '#/definitions/AcceptInform'
 /acceptRules:
   post:
     tags:
       - 接报设置管理infoConfig
     summary: '接报要求设置'
     operationId: addAcceptRule
     parameters:
       - name: AcceptReq
         in: body
         required: true
         schema:
           $ref: '#/definitions/AcceptRule'
     responses:
       200:
         description: OK
         schema:
           $ref: '#/definitions/ReturnResult'
 /acceptRules/{id}:
   put:
     tags:
       - 接报设置管理infoConfig
     summary: '修改接报要求信息'
     operationId: updateAcceptRule
     parameters:
       - $ref: '#/parameters/id-p'
       - name: sms
         in: body
         required: true
         schema:
           $ref: '#/definitions/AcceptRule'
     responses:
       200:
         description: OK
         schema:
           $ref: '#/definitions/ReturnResult'
 /acceptRules/getRuleSetting:
   post:
     tags:
       - 接报设置管理infoConfig
     summary: '根据条件查询接报要求'
     operationId: findAcceptRules
     parameters:
       - name: acceptReqVO
         in: body
         required: true
         schema:
           type: object
           properties:
             eventTypeId:
                type: string
     responses:
       200:
         description: OK
         schema:
           type: object
           allOf:
             - $ref: '#/definitions/ReturnResult'
           properties:
             data:
               $ref: '#/definitions/AcceptRule'

definitions:
  IMAccept:
    type: object
    properties:
      id:
        type: string
      eventName:
        type: string
        description: 列表显示
      position:
        type: string
      lonAndLat:
        type: string
      occurTime:
        type: string
        description: 列表显示
      eventTypeId:
        type: string
      eventTypeName:
        type: string
        description: 列表显示
      eventGradeId:
        type: string
      eventGradeName:
        type: string
        description: 列表显示
      reportOrgId:
        type: string
      reportOrgName:
        type: string
      reporter:
        type: string
      reporterTel:
        type: string
      methodId:
        type: string
      methodName:
        type: string
      reportTime:
        type: string
        format: date-time
        description: 列表显示
      eventCause:
        type: string
      eventDesc:
        type: string
      protreatment:
        type: string
      deathNum:
        type: integer
      wondedNum:
        type: integer
      request:
        type: string
      isFirst:
        type: string
        description: 列表显示，是否初报，0初报，1续报
        enum:
          - 0
          - 1
      firstReportId:
        type: string
        description: 首报Id
      createOrgId:
        type: string
        description: 创建单位ID
  IMAcceptVo:
    type: object
    properties:
      imAccept:
        $ref: '#/definitions/IMAccept'
      fileIds:
        type: array
        items:
          type: string
          description: 接报信息相关附件ID
      fileDeleteIds:
        type: array
        items:
          type: string
          description: 删除的附件ID数组
  IMAcceptList:
    type: object
    allOf:
      - $ref: '#/definitions/ReturnResult'
    properties:
      data:
        type: object
        properties:
          totalElements:
            type: integer
            description: 记录总数
          totalPages:
            type: integer
            description: 总页数
          first:
            type: boolean
            description: 是否第一页
          last:
            type: boolean
            description: 是否最后一页
          number:
            type: integer
            description: 当前页数，页码从0开始
          size:
            type: integer
            description: 每页记录数
          sort:
            type: string
          numberOfElements:
            type: integer
            description: 返回记录条数
          content:
            type: array
            items:
              $ref: '#/definitions/IMAccept'
  IMAcceptDeal:
    type: object
    properties:
      id:
        type: string
      acceptId:
        type: string
        description: 接报信息ID
      createOrgId:
        type: string
        description: 创建单位ID
      createOrgName:
        type: string
      dealOrgId:
        type: string
      dealOrgName:
        type: string
      dealFlag:
        type: string
        description: 接收后处理状态：0未发送，1已发送，2已退回，3已办结，4已生成事件
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
      dealTime:
        type: string
        format: 'date-time'
      returnReason:
        type: string
      eventId:
        type: string
      dealPersonId:
        type: string
      dealPersonNAme:
        type: string
  ####AccpetInform####
  AcceptInform:
    type: object
    properties:
      id:
        type: string
      orgName:
        type: string
        description: 列表显示
      orgDuty:
        type: string
        description: 列表显示
      principalId:
        type: string
      principal:
        type: string
        description: 列表显示
      principalTel:
        type: string
        description: 列表显示
      eventTypeId:
        type: string
      eventTypeName:
        type: string
  ####AcceptRule####
  AcceptRule:
    type: object
    properties:
      id:
        type: string
      ruleContent:
        type: string
        description: 列表显示
      eventTypeId:
        type: string
      eventTypeName:
        type: string
##### common model####
  SearchBody:
    type: object
    properties:
      page:
        type: integer
      size:
        type: integer
  ReturnResult:
    type: object
    properties:
      code:
        type: integer
        description: >-
          2000 操作成功
          4000 操作失败
          4001 验证码出错
          4002 用户名或密码错误
          5000 后台逻辑错误
          5001 令牌失效或过期
          5009 未知错误
      msg:
        type: string
#### parameters####
parameters:
  id-p:
    name: id
    in: path
    required: true
    description: 主键ID
    type: string



